name = "SparseArrayVectors"
uuid = "82bac53c-503e-4ed7-bd05-09ef753e0dd4"
authors = ["SixZero <havliktomi@hotmail.com>"]
version = "0.1.0"

[deps]
Boilerplate = "fe7df2fb-dcb5-4bf9-996b-0af1f7856ff2"
ZygoteExtensions = "5403f96b-0061-4db3-b58b-91317ba4c332"
